FROM docker.io/library/debian:bookworm-slim

ARG JITSI_RELEASE=stable
ENV JITSI_RELEASE=${JITSI_RELEASE}
ENV S6_BEHAVIOUR_IF_STAGE2_FAILS=2

COPY base/rootfs/ /
COPY base/scripts/setup-base.sh /tmp/setup-base.sh

RUN /bin/bash /tmp/setup-base.sh && rm /tmp/setup-base.sh

LABEL org.opencontainers.image.title="Jitsi Meet"
LABEL org.opencontainers.image.description="WebRTC compatible JavaScript application that uses Jitsi Videobridge to provide high quality, scalable video conferences."
LABEL org.opencontainers.image.url="https://jitsi.org/jitsi-meet/"
LABEL org.opencontainers.image.source="https://github.com/jitsi/docker-jitsi-meet"
LABEL org.opencontainers.image.documentation="https://jitsi.github.io/handbook/"

ADD https://raw.githubusercontent.com/acmesh-official/acme.sh/3.0.7/acme.sh /opt
COPY web/rootfs/ /

RUN apt-dpkg-wrap apt-get update && \
    apt-dpkg-wrap apt-get install -y dnsutils cron nginx-extras jitsi-meet-web socat curl jq && \
    mv /usr/share/jitsi-meet/interface_config.js /defaults && \
    rm -f /etc/nginx/conf.d/default.conf && \
    apt-cleanup

EXPOSE 80 443

ENTRYPOINT [ "/init" ]

VOLUME ["/config", "/usr/share/jitsi-meet/transcripts"]
