FROM alphacep/kaldi-vosk-server

RUN pip3 install --upgrade 'websockets<14.0'

RUN mkdir /opt/vosk-model-vn \
  && cd /opt/vosk-model-vn \
  && wget -q http://alphacephei.com/kaldi/models/vosk-model-vn-0.4.zip \
  && unzip vosk-model-vn-0.4.zip \
  && mv vosk-model-vn-0.4 model \
  && rm -rf vosk-model-vn-0.4.zip

EXPOSE 2700
WORKDIR /opt/vosk-server/websocket
CMD [ "python3", "./asr_server.py", "/opt/vosk-model-vn/model" ]