import { auth } from '@/lib/auth'
import { headers } from 'next/headers'
import { redirect } from 'next/navigation'
import { DashboardShell } from '@/components/layout/dashboard-shell'
import { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Meeting Meeta',
    description: 'Generated by Meeta App With Jitsi SDK',
}

export default async function DashboardLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const session = await auth.api.getSession({
        headers: await headers(),
    })

    if (!session?.user) {
        redirect('/login')
    }

    return <DashboardShell>{children}</DashboardShell>
}
